In [ ]:
import pandas as pd
from shapely.geometry import Point, Polygon

# Load your rainfall data
rainfall_data = pd.read_csv('rainfall_data.csv')

# Define your boundary polygon (lon, lat order!)
boundary_coords = [
    (110.26058, -7.16924),
    (110.52927, -7.16689),
    (110.53222, -6.92284),
    (110.26007, -6.92160)
]
boundary_polygon = Polygon(boundary_coords)

# Function to check if a point is inside the polygon
def is_inside(lat, lon):
    return boundary_polygon.contains(Point(lon, lat))

# Apply the function to filter data
rainfall_data['inside'] = rainfall_data.apply(lambda row: is_inside(row['Lat_DD'], row['Lon_DD']), axis=1)

# Keep only rows inside the boundary
filtered_data = rainfall_data[rainfall_data['inside']].drop(columns=['inside'])

# Save filtered data
filtered_data.to_csv('rainfall_data_filtered.csv', index=False)

print(f"Original data: {len(rainfall_data)} rows")
print(f"Filtered data: {len(filtered_data)} rows")

In [2]:
import pandas as pd
rainfall_data = pd.read_csv('rainfall_data.csv')

In [3]:
rainfall_data

,location_name,watershed_name,rainfall(mm),Lat_DD,Lon_DD,date,year,UTM_Easting,UTM_Northing,UTM_Zone
0,Bandungan,DAS Tuntang,16.4,-7.228842,110.349875,2021-01-01,2021,428227.075860,9.200902e+06,49S
1,Bandungan,DAS Tuntang,1.0,-7.228842,110.349875,2021-01-04,2021,428227.075860,9.200902e+06,49S
2,Bandungan,DAS Tuntang,6.3,-7.228842,110.349875,2021-01-05,2021,428227.075860,9.200902e+06,49S
3,Bandungan,DAS Tuntang,6.5,-7.228842,110.349875,2021-01-06,2021,428227.075860,9.200902e+06,49S
4,Bandungan,DAS Tuntang,0.0,-7.228842,110.349875,2021-01-07,2021,428227.075860,9.200902e+06,49S
...,...,...,...,...,...,...,...,...,...,...
17074,Wirosari Patean,Bodri,6.3,-7.190844,110.119711,2023-12-26,2023,402807.497118,9.205060e+06,49S
17075,Wirosari Patean,Bodri,0.0,-7.190844,110.119711,2023-12-27,2023,402807.497118,9.205060e+06,49S
17076,Wirosari Patean,Bodri,32.4,-7.190844,110.119711,2023-12-28,2023,402807.497118,9.205060e+06,49S
17077,Wirosari Patean,Bodri,2.7,-7.190844,110.119711,2023-12-29,2023,402807.497118,9.205060e+06,49S
17078,Wirosari Patean,Bodri,2.4,-7.190844,110.119711,2023-12-30,2023,402807.497118,9.205060e+06,49S